### ISSUE TITLE
Can't set adapter

### ISSUE THREAD

**Issue by Hassanmsaid** [smarteist/Android-Image-Slider#68]
When I write sliderView.setSliderAdapter(adapter) it shows me an error:
"setSliderAdapter (androidx.viewpager.widget.PagerAdapter) in SliderView cannot be applied
to (com.example.hostacare.SliderAdapterExample)" 
should I migrate the whole project to androidx ?!

**Comment by smarteist** [comment]
> When I write sliderView.setSliderAdapter(adapter) it shows me an error:
> "setSliderAdapter (androidx.viewpager.widget.PagerAdapter) in SliderView cannot be applied
> to (com.example.hostacare.SliderAdapterExample)"
> should I migrate the whole project to androidx ?!

You can add appcompat version instead .

**Comment by Hassanmsaid** [comment]
@smarteist Yes, I did it and it worked. Thank you

**Comment by Sarthak2601** [comment]
Hello, 
In the below lines of code I have a doubt. 
what are we calling in the imageViewBackground and textViewDescription ?
because if we see the other part of the code, we don't have any view by this name... 
So do we need to create one or is there something else that I am missing. 

public SliderAdapterVH(View itemView) {
                super(itemView);
                imageViewBackground = itemView.findViewById(R.id.iv_auto_image_slider);
                textViewDescription = itemView.findViewById(R.id.tv_auto_image_slider);
                this.itemView = itemView;
            }

Also In the inflate command 
View inflate = LayoutInflater.from(parent.getContext()).inflate(R.layout.image_slider_layout_item, null);

what do we set after layout. ? 
It shows error.

**Comment by RanaHakim** [comment]
@Hassanmsaid can you tell me how i make custom layout for slider items here

**Comment by Hassanmsaid** [comment]
@RanaHakim just change "image_slider_layout_item" as you want and bind its views in the adapter
